# ----------------------------------------------------------------------- #
#
# 1. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d
#
# 2. docker-compose -p comp3095-microservices-ecommerce -f docker-compose.yml up -d --build
# 2 - Forces a rebuild of all container images
#
# ----------------------------------------------------------------------- #

version: '3.9'

services:
  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service
      dockerfile: ./Dockerfile
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo
    networks:
      - spring

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: mongo
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: mongod --auth
    networks:
      - spring

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - spring

volumes:
  mongo:
    driver: local

networks:
  spring:
    driver: bridge